#!/usr/bin/env python3
"""
generate.py

Reads _data/entries.yml (the single file you hand-edit) and regenerates:
  - _data/songs.yml
  - _data/theory.yml

Usage:
    python3 scripts/generate.py

Run this from the repo root any time you add/edit an entry in entries.yml,
then commit the three files together (entries.yml + the two generated files).
"""

import sys
from pathlib import Path
from collections import OrderedDict

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
ENTRIES_PATH = REPO_ROOT / "_data" / "entries.yml"
SONGS_PATH = REPO_ROOT / "_data" / "songs.yml"
THEORY_PATH = REPO_ROOT / "_data" / "theory.yml"


def load_entries():
    with open(ENTRIES_PATH, "r", encoding="utf-8") as f:
        entries = yaml.safe_load(f) or []
    if not isinstance(entries, list):
        sys.exit(f"error: {ENTRIES_PATH} must contain a YAML list of entries")
    return entries


def validate_entry(entry, index):
    required = ["id", "composer", "title"]
    missing = [k for k in required if not entry.get(k)]
    if missing:
        sys.exit(
            f"error: entries.yml entry #{index + 1} is missing required "
            f"field(s): {', '.join(missing)}"
        )
    for t_index, topic in enumerate(entry.get("topics", [])):
        if not topic.get("category"):
            sys.exit(
                f"error: entries.yml entry '{entry['id']}' topic #{t_index + 1} "
                f"is missing 'category'"
            )
        if not topic.get("techniques"):
            sys.exit(
                f"error: entries.yml entry '{entry['id']}' topic "
                f"'{topic.get('category')}' has no 'techniques'"
            )


def build_songs(entries):
    songs = OrderedDict()
    for entry in entries:
        song = OrderedDict(
            [
                ("composer", entry["composer"]),
                ("title", entry["title"]),
            ]
        )
        # `page` is optional — omit it entirely (rather than writing a null)
        # if the example page doesn't exist yet. index.md checks for this
        # and renders the song as plain text instead of a link.
        if entry.get("page"):
            song["page"] = entry["page"]
        songs[entry["id"]] = song
    return songs


def build_theory(entries):
    """
    Produces a list shaped like:

    - category: Secondary Dominants
      examples: []                 # entries filed directly under the category
      subcategories:
        V/vi:
          examples:
            - song: some-id
              techniques: ["V7/vi"]
        V/ii:
          examples: [...]

    Categories/subcategories are kept in first-seen order so the site's
    order roughly follows the order you added things in entries.yml.
    """
    categories = OrderedDict()

    for entry in entries:
        song_id = entry["id"]
        for topic in entry.get("topics", []):
            category = topic["category"]
            subcategory = topic.get("subcategory")
            techniques = topic["techniques"]

            if category not in categories:
                categories[category] = OrderedDict(
                    [("examples", []), ("subcategories", OrderedDict())]
                )

            example = OrderedDict([("song", song_id), ("techniques", techniques)])

            if subcategory:
                subcats = categories[category]["subcategories"]
                if subcategory not in subcats:
                    subcats[subcategory] = OrderedDict([("examples", [])])
                subcats[subcategory]["examples"].append(example)
            else:
                categories[category]["examples"].append(example)

    # Convert to the final list-of-dicts shape, dropping empty keys so the
    # YAML output stays clean (no stray `examples: []` / `subcategories: {}`)
    theory = []
    for category, data in categories.items():
        entry_out = OrderedDict([("category", category)])
        if data["examples"]:
            entry_out["examples"] = data["examples"]
        if data["subcategories"]:
            entry_out["subcategories"] = data["subcategories"]
        theory.append(entry_out)

    return theory


def represent_ordereddict(dumper, data):
    return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())


def dump_yaml(data, path, header):
    yaml.add_representer(OrderedDict, represent_ordereddict)
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(
            data,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=1000,
        )


def main():
    entries = load_entries()
    for i, entry in enumerate(entries):
        validate_entry(entry, i)

    songs = build_songs(entries)
    theory = build_theory(entries)

    dump_yaml(
        songs,
        SONGS_PATH,
        "# AUTO-GENERATED by scripts/generate.py from _data/entries.yml\n"
        "# Do not edit by hand — edit _data/entries.yml and re-run the script.\n",
    )
    dump_yaml(
        theory,
        THEORY_PATH,
        "# AUTO-GENERATED by scripts/generate.py from _data/entries.yml\n"
        "# Do not edit by hand — edit _data/entries.yml and re-run the script.\n",
    )

    print(f"Wrote {SONGS_PATH.relative_to(REPO_ROOT)} ({len(songs)} song(s))")
    print(f"Wrote {THEORY_PATH.relative_to(REPO_ROOT)} ({len(theory)} categor{'y' if len(theory) == 1 else 'ies'})")


if __name__ == "__main__":
    main()
